PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 22,
  "title": "susuPatch",
  "postType": "post",
  "status": "published",
  "content": "test content",
  "metaOptions" : {
    "metaValue": "{ \"sidebarEnabled\": true, \"footerActive\": true }"
    },
  "tags": [3,4]
}