POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName":"Hash",
    "lastName":"hhhh",
    "email":"hashh@mail.com",
    "password":"kurongCute333!"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiaGFzaGhAbWFpbC5jb20iLCJpYXQiOjE3MzI1MjMwMDQsImV4cCI6MTczMjUyNjYwNCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.yiF99B52M8O85GhijWU-RY3xU-2u5FtMOkgEvX5iIwc
{
"users": [
    {
      "firstName": "Mark",
      "lastName": "Doe",
      "email": "mark@doe.com",
      "password": "Password123#"
    },
    {
      "firstName": "Tom",
      "lastName": "Doe",
      "email": "tom@doe.com",
      "password": "Password123#"
    }
  ]
}